
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND COMMA IMPLY LPAREN NOT OR RPAREN VARaxiom : LPAREN IMPLY COMMA expression COMMA LPAREN IMPLY COMMA expression COMMA expression RPAREN RPARENaxiom : LPAREN IMPLY COMMA LPAREN IMPLY COMMA expression COMMA expression RPAREN COMMA LPAREN IMPLY COMMA LPAREN IMPLY COMMA expression COMMA LPAREN IMPLY COMMA expression COMMA expression RPAREN RPAREN COMMA LPAREN IMPLY COMMA expression COMMA expression RPAREN RPAREN RPARENaxiom : LPAREN IMPLY COMMA expression COMMA LPAREN IMPLY COMMA expression COMMA LPAREN AND COMMA expression COMMA expression RPAREN RPAREN RPARENaxiom : LPAREN IMPLY COMMA LPAREN AND COMMA expression COMMA expression RPAREN COMMA expression RPARENaxiom : LPAREN IMPLY COMMA expression COMMA LPAREN OR COMMA expression COMMA expression RPAREN RPARENaxiom : LPAREN IMPLY COMMA LPAREN IMPLY COMMA expression COMMA expression RPAREN COMMA LPAREN IMPLY COMMA LPAREN IMPLY COMMA expression COMMA expression RPAREN COMMA LPAREN IMPLY COMMA LPAREN OR COMMA expression COMMA expression RPAREN COMMA expression RPAREN RPAREN RPARENaxiom : LPAREN IMPLY COMMA LPAREN IMPLY COMMA expression COMMA expression RPAREN COMMA LPAREN IMPLY COMMA LPAREN IMPLY COMMA expression COMMA LPAREN NOT expression RPAREN RPAREN COMMA LPAREN NOT expression RPAREN RPAREN RPARENaxiom : LPAREN IMPLY COMMA LPAREN NOT LPAREN NOT expression RPAREN RPAREN COMMA expression RPARENexpression : axiomexpression : VAR'
    
_lr_action_items = {'LPAREN':([0,4,11,12,13,14,19,22,23,25,26,37,38,39,40,41,42,53,57,61,64,67,71,76,78,80,84,88,89,94,96,98,104,105,110,111,],[2,5,15,16,5,2,2,27,2,2,2,43,2,5,47,2,2,60,2,63,2,2,73,2,5,83,27,91,92,2,99,2,2,2,2,2,]),'$end':([1,55,56,58,59,72,106,118,119,],[0,-4,-8,-1,-5,-3,-7,-2,-6,]),'IMPLY':([2,5,16,27,43,47,60,63,73,83,99,],[3,9,20,33,3,54,33,65,75,86,102,]),'COMMA':([3,6,7,8,9,10,17,18,20,21,31,32,33,34,35,36,46,50,54,55,56,58,59,62,65,69,72,75,77,81,85,86,93,95,101,102,106,108,109,118,119,],[4,12,-9,-10,13,14,22,23,25,26,37,38,39,40,41,42,53,57,61,-4,-8,-1,-5,64,67,71,-3,78,80,84,88,89,96,98,104,105,-7,110,111,-2,-6,]),'VAR':([4,13,14,19,22,23,25,26,37,38,39,41,42,53,57,64,67,71,76,78,84,94,98,104,105,110,111,],[8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,]),'AND':([5,43,60,],[10,50,50,]),'NOT':([5,15,73,91,],[11,19,76,94,]),'RPAREN':([7,8,24,28,29,30,44,45,48,49,51,52,55,56,58,59,66,68,70,72,74,79,82,87,90,97,100,103,106,107,112,113,114,115,116,117,118,119,],[-9,-10,30,34,35,36,51,52,55,56,58,59,-4,-8,-1,-5,68,70,72,-3,77,82,85,90,93,100,103,106,-7,109,114,115,116,117,118,119,-2,-6,]),'OR':([16,27,60,92,],[21,21,21,95,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'axiom':([0,4,13,14,19,22,23,25,26,37,38,39,41,42,53,57,64,67,71,76,78,84,94,98,104,105,110,111,],[1,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,]),'expression':([4,13,14,19,22,23,25,26,37,38,39,41,42,53,57,64,67,71,76,78,84,94,98,104,105,110,111,],[6,17,18,24,28,29,31,32,44,45,46,48,49,44,62,66,69,74,79,81,87,97,101,107,108,112,113,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> axiom","S'",1,None,None,None),
  ('axiom -> LPAREN IMPLY COMMA expression COMMA LPAREN IMPLY COMMA expression COMMA expression RPAREN RPAREN','axiom',13,'p_axiom_1','d.py',53),
  ('axiom -> LPAREN IMPLY COMMA LPAREN IMPLY COMMA expression COMMA expression RPAREN COMMA LPAREN IMPLY COMMA LPAREN IMPLY COMMA expression COMMA LPAREN IMPLY COMMA expression COMMA expression RPAREN RPAREN COMMA LPAREN IMPLY COMMA expression COMMA expression RPAREN RPAREN RPAREN','axiom',37,'p_axiom_2','d.py',61),
  ('axiom -> LPAREN IMPLY COMMA expression COMMA LPAREN IMPLY COMMA expression COMMA LPAREN AND COMMA expression COMMA expression RPAREN RPAREN RPAREN','axiom',19,'p_axiom_3','d.py',69),
  ('axiom -> LPAREN IMPLY COMMA LPAREN AND COMMA expression COMMA expression RPAREN COMMA expression RPAREN','axiom',13,'p_axiom_4_5','d.py',77),
  ('axiom -> LPAREN IMPLY COMMA expression COMMA LPAREN OR COMMA expression COMMA expression RPAREN RPAREN','axiom',13,'p_axiom_6_7','d.py',90),
  ('axiom -> LPAREN IMPLY COMMA LPAREN IMPLY COMMA expression COMMA expression RPAREN COMMA LPAREN IMPLY COMMA LPAREN IMPLY COMMA expression COMMA expression RPAREN COMMA LPAREN IMPLY COMMA LPAREN OR COMMA expression COMMA expression RPAREN COMMA expression RPAREN RPAREN RPAREN','axiom',37,'p_axiom_8','d.py',103),
  ('axiom -> LPAREN IMPLY COMMA LPAREN IMPLY COMMA expression COMMA expression RPAREN COMMA LPAREN IMPLY COMMA LPAREN IMPLY COMMA expression COMMA LPAREN NOT expression RPAREN RPAREN COMMA LPAREN NOT expression RPAREN RPAREN RPAREN','axiom',31,'p_axiom_9','d.py',111),
  ('axiom -> LPAREN IMPLY COMMA LPAREN NOT LPAREN NOT expression RPAREN RPAREN COMMA expression RPAREN','axiom',13,'p_axiom_10','d.py',119),
  ('expression -> axiom','expression',1,'p_expression_axiom','d.py',127),
  ('expression -> VAR','expression',1,'p_expression_var','d.py',131),
]
