
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND COMMA IMPLY INF LPAREN NOT OR RPAREN SCOLON VARexpression : LPAREN INF SCOLON expression SCOLON expression RPARENexpression : LPAREN COMMA SCOLON expression SCOLON expression RPARENexpression : LPAREN IMPLY SCOLON expression SCOLON expression RPAREN\n\t| LPAREN OR SCOLON expression SCOLON expression RPAREN\n\t| LPAREN AND SCOLON expression SCOLON expression RPARENexpression : LPAREN NOT expression RPARENexpression : VARexpression : axiomaxiom : LPAREN IMPLY SCOLON expression SCOLON LPAREN IMPLY SCOLON expression SCOLON expression RPAREN RPARENaxiom : LPAREN IMPLY SCOLON LPAREN IMPLY SCOLON expression SCOLON expression RPAREN SCOLON LPAREN IMPLY SCOLON LPAREN IMPLY SCOLON expression SCOLON LPAREN IMPLY SCOLON expression SCOLON expression RPAREN RPAREN SCOLON LPAREN IMPLY SCOLON expression SCOLON expression RPAREN RPAREN RPARENaxiom : LPAREN IMPLY SCOLON expression SCOLON LPAREN IMPLY SCOLON expression SCOLON LPAREN AND SCOLON expression SCOLON expression RPAREN RPAREN RPARENaxiom : LPAREN IMPLY SCOLON LPAREN AND SCOLON expression SCOLON expression RPAREN SCOLON expression RPARENaxiom : LPAREN IMPLY SCOLON expression SCOLON LPAREN OR SCOLON expression SCOLON expression RPAREN RPARENaxiom : LPAREN IMPLY SCOLON LPAREN IMPLY SCOLON expression SCOLON expression RPAREN SCOLON LPAREN IMPLY SCOLON LPAREN IMPLY SCOLON expression SCOLON expression RPAREN SCOLON LPAREN IMPLY SCOLON LPAREN OR SCOLON expression SCOLON expression RPAREN SCOLON expression RPAREN RPAREN RPARENaxiom : LPAREN IMPLY SCOLON LPAREN IMPLY SCOLON expression SCOLON expression RPAREN SCOLON LPAREN IMPLY SCOLON LPAREN IMPLY SCOLON expression SCOLON LPAREN NOT expression RPAREN RPAREN SCOLON LPAREN NOT expression RPAREN RPAREN RPARENaxiom : LPAREN IMPLY SCOLON LPAREN NOT LPAREN NOT expression RPAREN RPAREN SCOLON expression RPAREN'
    
_lr_action_items = {'LPAREN':([0,10,11,12,13,14,15,24,25,28,29,30,31,34,35,45,51,52,54,55,64,65,66,67,68,81,84,87,90,94,99,101,103,107,111,112,117,119,121,127,128,133,134,],[2,2,2,2,19,2,2,2,2,36,37,2,2,19,2,2,37,2,19,2,69,2,72,2,2,2,86,2,2,96,2,19,106,37,114,115,2,122,2,2,2,2,2,]),'VAR':([0,10,11,12,13,14,15,24,25,28,29,30,31,34,35,45,51,52,54,55,64,65,67,68,81,87,90,94,99,101,107,117,121,127,128,133,134,],[3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,]),'$end':([1,3,4,23,41,42,48,49,50,79,80,82,83,95,129,141,142,],[0,-7,-8,-6,-1,-2,-3,-4,-5,-12,-16,-9,-13,-11,-15,-10,-14,]),'INF':([2,19,36,37,69,96,],[5,5,5,5,5,5,]),'COMMA':([2,19,36,37,69,96,],[6,6,6,6,6,6,]),'IMPLY':([2,19,36,37,69,72,86,96,106,122,],[7,26,7,46,46,78,88,98,109,125,]),'OR':([2,19,36,37,69,96,115,],[8,8,8,47,47,8,118,]),'AND':([2,19,36,37,69,96,],[9,27,9,9,75,9,]),'NOT':([2,19,36,37,69,96,114,],[10,28,45,10,10,99,117,]),'RPAREN':([3,4,16,23,32,33,38,39,40,41,42,48,49,50,53,56,57,58,70,71,73,74,76,77,79,80,82,83,89,91,93,95,97,102,105,110,113,120,123,126,129,130,135,136,137,138,139,140,141,142,],[-7,-8,23,-6,41,42,48,49,50,-1,-2,-3,-4,-5,58,61,62,63,76,77,79,80,82,83,-12,-16,-9,-13,91,93,95,-11,100,105,108,113,116,123,126,129,-15,132,137,138,139,140,141,142,-10,-14,]),'SCOLON':([3,4,5,6,7,8,9,17,18,20,21,22,23,26,27,41,42,43,44,46,47,48,49,50,59,60,61,62,63,75,78,79,80,82,83,85,88,92,95,98,100,104,108,109,116,118,124,125,129,131,132,141,142,],[-7,-8,11,12,13,14,15,24,25,29,30,31,-6,34,35,-1,-2,51,52,54,55,-3,-4,-5,64,65,66,67,68,81,84,-12,-16,-9,-13,87,90,94,-11,101,103,107,111,112,119,121,127,128,-15,133,134,-10,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,10,11,12,13,14,15,24,25,28,29,30,31,34,35,45,51,52,54,55,64,65,67,68,81,87,90,94,99,101,107,117,121,127,128,133,134,],[1,16,17,18,20,21,22,32,33,16,38,39,40,43,44,53,56,57,59,60,70,71,73,74,85,89,92,97,102,104,110,120,124,130,131,135,136,]),'axiom':([0,10,11,12,13,14,15,24,25,28,29,30,31,34,35,45,51,52,54,55,64,65,67,68,81,87,90,94,99,101,107,117,121,127,128,133,134,],[4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> LPAREN INF SCOLON expression SCOLON expression RPAREN','expression',7,'p_expression_inf','d.py',67),
  ('expression -> LPAREN COMMA SCOLON expression SCOLON expression RPAREN','expression',7,'p_expression_comma','d.py',73),
  ('expression -> LPAREN IMPLY SCOLON expression SCOLON expression RPAREN','expression',7,'p_expression_binary','d.py',82),
  ('expression -> LPAREN OR SCOLON expression SCOLON expression RPAREN','expression',7,'p_expression_binary','d.py',83),
  ('expression -> LPAREN AND SCOLON expression SCOLON expression RPAREN','expression',7,'p_expression_binary','d.py',84),
  ('expression -> LPAREN NOT expression RPAREN','expression',4,'p_expression_unary','d.py',90),
  ('expression -> VAR','expression',1,'p_expression_var','d.py',96),
  ('expression -> axiom','expression',1,'p_expression_axiom','d.py',100),
  ('axiom -> LPAREN IMPLY SCOLON expression SCOLON LPAREN IMPLY SCOLON expression SCOLON expression RPAREN RPAREN','axiom',13,'p_axiom_1','d.py',104),
  ('axiom -> LPAREN IMPLY SCOLON LPAREN IMPLY SCOLON expression SCOLON expression RPAREN SCOLON LPAREN IMPLY SCOLON LPAREN IMPLY SCOLON expression SCOLON LPAREN IMPLY SCOLON expression SCOLON expression RPAREN RPAREN SCOLON LPAREN IMPLY SCOLON expression SCOLON expression RPAREN RPAREN RPAREN','axiom',37,'p_axiom_2','d.py',114),
  ('axiom -> LPAREN IMPLY SCOLON expression SCOLON LPAREN IMPLY SCOLON expression SCOLON LPAREN AND SCOLON expression SCOLON expression RPAREN RPAREN RPAREN','axiom',19,'p_axiom_3','d.py',124),
  ('axiom -> LPAREN IMPLY SCOLON LPAREN AND SCOLON expression SCOLON expression RPAREN SCOLON expression RPAREN','axiom',13,'p_axiom_4_5','d.py',134),
  ('axiom -> LPAREN IMPLY SCOLON expression SCOLON LPAREN OR SCOLON expression SCOLON expression RPAREN RPAREN','axiom',13,'p_axiom_6_7','d.py',151),
  ('axiom -> LPAREN IMPLY SCOLON LPAREN IMPLY SCOLON expression SCOLON expression RPAREN SCOLON LPAREN IMPLY SCOLON LPAREN IMPLY SCOLON expression SCOLON expression RPAREN SCOLON LPAREN IMPLY SCOLON LPAREN OR SCOLON expression SCOLON expression RPAREN SCOLON expression RPAREN RPAREN RPAREN','axiom',37,'p_axiom_8','d.py',168),
  ('axiom -> LPAREN IMPLY SCOLON LPAREN IMPLY SCOLON expression SCOLON expression RPAREN SCOLON LPAREN IMPLY SCOLON LPAREN IMPLY SCOLON expression SCOLON LPAREN NOT expression RPAREN RPAREN SCOLON LPAREN NOT expression RPAREN RPAREN RPAREN','axiom',31,'p_axiom_9','d.py',178),
  ('axiom -> LPAREN IMPLY SCOLON LPAREN NOT LPAREN NOT expression RPAREN RPAREN SCOLON expression RPAREN','axiom',13,'p_axiom_10','d.py',188),
]
